### ISSUE TITLE
Hide inherited @hidden entries from intellisense

### ISSUE THREAD

**Issue by Zyrakia** [Fireboltofdeath/roblox-ts-extensions#6]
Would this be a possibility? Not exactly sure how vscode extensions work, but if possible it'd be nice.

```ts
interface OnTest {
    /** @hidden */
    onTest(): void;
}

class Test implements OnTest {
    public onTest() {}
}

// It'd be neat if this entry was hidden, but currently it is not
new Test().onTest()
```

**Comment by Dionysusnu** [comment]
https://github.com/roblox-ts/roblox-ts-extensions/blob/a7f9f63b0b228c57efd663f6cc1f817d650dd4d3/src/languageService/getCompletionsAtPosition.ts#L45-L56
Currently checked here, we'd have to find a way to get the symbol it's inherited from. I'm not sure how easy that is.

**Comment by Fireboltofdeath** [comment]
I've added support for any JSDoc tags being inherited and I've also added a `@hideinherited` tag which can be used to only hide from intellisense when it is inherited, so that you still get autocorrection for the interface member itself if you're trying to use it.
