### ISSUE TITLE
roblox-ts extension making vscode laggy

### ISSUE THREAD

**Issue by sivakwork** [Fireboltofdeath/roblox-ts-extensions#7]
the roblox-ts extension is causing vsc to become laggy overtime for some reason this could be something related to garbage collection but it's very annoying

**Comment by wad4444** [comment]
afaik this issue is known and exist for a long time

**Comment by sivakwork** [comment]
> afaik this issue is known and exist for a long time

Yeah but no one opened an issue for it, hopefully it gets fixed.

**Comment by Fireboltofdeath** [comment]
This should hopefully be fixed with version 1.6.2 of the vscode extension. Let me know if you still encounter it.
